# Generated by Django 6.0.5 on 2026-06-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sandals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sandals/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sandals',
            },
        ),
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='coats',
            options={'verbose_name_plural': 'Coats'},
        ),
        migrations.AlterModelOptions(
            name='pants',
            options={'verbose_name_plural': 'Pants'},
        ),
        migrations.AlterModelOptions(
            name='perfumes',
            options={'verbose_name_plural': 'Perfumes'},
        ),
        migrations.AlterModelOptions(
            name='shirts',
            options={'verbose_name_plural': 'Shirts'},
        ),
        migrations.AlterModelOptions(
            name='shoes',
            options={'verbose_name_plural': 'Shoes'},
        ),
        migrations.AlterModelOptions(
            name='tshirt',
            options={'verbose_name_plural': 'Tshirt'},
        ),
        migrations.AlterModelOptions(
            name='watches',
            options={'verbose_name_plural': 'Watches'},
        ),
    ]
