# Generated by Django 6.0.5 on 2026-06-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiva', '0002_sandals_alter_cart_options_alter_coats_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cart/'),
        ),
        migrations.AlterField(
            model_name='coats',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='coats/'),
        ),
        migrations.AlterField(
            model_name='pants',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pants/'),
        ),
        migrations.AlterField(
            model_name='perfumes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
        migrations.AlterField(
            model_name='sandals',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sandals/'),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shirts/'),
        ),
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoes/'),
        ),
        migrations.AlterField(
            model_name='tshirt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tshirts/'),
        ),
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='watches/'),
        ),
    ]
