# Generated by Django 6.0.5 on 2026-07-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiva', '0006_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('coats', 'Coats'), ('shirts', 'Shirts'), ('pants', 'Pants'), ('tshirt', 'Tshirt'), ('watches', 'Watches'), ('perfumes', 'Perfumes'), ('shoes', 'Shoes'), ('sandals', 'Sandals')], max_length=20)),
                ('product_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')])),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
